services:
  rendezvous:
    build: https://github.com/binarybaron/rendezvous-server.git
    restart: unless-stopped
    container_name: rendezvous
    volumes:
      - 'rendezvous-data:/data/'
    ports:
      - '0.0.0.0:${RENDEZVOUS_PORT:-8888}:${RENDEZVOUS_PORT:-8888}'
    entrypoint: ''
    command: >
      sh -c "rendezvous-server --listen-tcp=${RENDEZVOUS_PORT:-8888} --secret-file=/data/rendezvous_secret --generate-secret || true &&
             rendezvous-server --listen-tcp=${RENDEZVOUS_PORT:-8888} --secret-file=/data/rendezvous_secret"
volumes:
  rendezvous-data:
